### ISSUE TITLE
hardcoded HyCreate version in hypy

### ISSUE THREAD

**Issue by MaxGaukler** [verivital/hyst#47]
hypy expects "HyCreate2.8.jar" because the name is hardcoded in tool_hycreate.py, however the latest release from the [website](http://stanleybak.com/projects/hycreate/hycreate.html) is "HyCreate 2.81.jar".

(I don't think this is a big problem -- I just want to make sure all issues that require a workaround in the automatic build (#42) are properly reported)

**Comment by stanleybak** [comment]
updated to 2.81 in my fork (will merge soon): https://github.com/stanleybak/hyst/commit/93552275fe94229bcbb74435d6309ce95f969d40#diff-10b706758a922be426ea5caed09b50a7
