### ISSUE TITLE
Flowstar printer fails with german locale

### ISSUE THREAD

**Issue by MaxGaukler** [verivital/hyst#48]
The stepsize setting in the flowstar output uses the wrong decimal separator (comma) if a German locale is used. Setting `LANG=en_US.UTF-8` or `LANG=C` is a workaround.
```
u@vm:/opt/hyst$ LANG=de_DE.UTF-8 java -jar src/Hyst.jar -t flowstar '' -i examples/toy/toy.xml | grep "fixed steps"
        fixed steps 0,1
u@vm:/opt/hyst$ LANG=en_US.UTF-8 java -jar src/Hyst.jar -t flowstar '' -i examples/toy/toy.xml | grep "fixed steps"
        fixed steps 0.1
```

**Comment by stanleybak** [comment]
fixed in my fork (will merge soon): https://github.com/stanleybak/hyst/commit/d48158ea721106f0422ceaa5a612c60997248f7e

please comment if it's still broken
