### ISSUE TITLE
HyCreate printer: syntax error for reset variables

### ISSUE THREAD

**Issue by MaxGaukler** [verivital/hyst#50]
The following SpaceEx example file causes a syntax error (Compilation failed). Prepending "$" to the variable name in the transition's reset action fixes the error.

Example SpaceEx file and conversion result: https://gist.github.com/MaxGaukler/f943bbff3809bd3ccf83ce16b11f10a5

```
java -jar src/Hyst.jar -t hycreate '' -i foo.xml -o foo.hyc2
java -jar /opt/tools/hycreate/HyCreate2.81/HyCreate2.81.jar foo.hyc2
```

Press "Compile":
```
Compiling generated java code files (14 files)
automaton/Transition0_loc1_to_loc1_Reset.java:12: error: cannot find symbol
x2.set(_input.dims[DimensionNames.x1.ordinal()].min, _input.dims[DimensionNames.x1.ordinal()].max);
^
  symbol:   variable x2
  location: class Transition0_loc1_to_loc1_Reset
1 error
ERROR: compiler.CompilationException: Error compiling generated java code.
```

**Comment by stanleybak** [comment]
fixed in my fork (will merge soon): https://github.com/stanleybak/hyst/commit/06937ec66f7a813137c47efd4bf867d06ea9b2c6
