### ISSUE TITLE
Hypy: Python 3 Compatibility

### ISSUE THREAD

**Issue by MaxGaukler** [verivital/hyst#57]
Hypy currently only supports Python2, which is no longer maintained after the end of the year. Many packages are also dropping Python2 support (see https://python3statement.org/ ), or have already done so, so it is difficult to write code which combines Hypy and other packages.

Therefore it would be great to make Hypy compatible with Python3. As it's possible to make code compatible with both Python2 and Python3 (see https://python-future.org/ ), that would probably be the best way to go.

**Comment by stanleybak** [comment]
Hi Max,

This is a good idea. Do you have any cycles to work together on this? We could make it its own project separate from Hyst.

**Comment by MaxGaukler** [comment]
Hi Stan,

I'm not sure if detaching hypy from hyst is helpful or not, but I would be happy either way.

I probably won't have the time to do the whole Python3 conversion on my own, but would be happy to cooperate.

Suggested steps:

- measure test coverage to find out what we test and what not (not so easy because of subprocesses, but there is a solution: https://coverage.readthedocs.io/en/latest/subprocess.html )
- ensure test coverage: It seems most of the python files are used by src/tests/integration/run_tests.py , but I'm not sure if e.g. strategy.py is tested by anything. If any files are untested, either test or drop them.
- (already done:) include Python2 tests in CI
- "automatic" conversion to Python3 using futurize
- fix all tests in Python2 and Python3 (this may be tedious or easy, depending on our luck)
- include Python3 tests in CI

My goal would be to have most of these done by the end of the year, so I can drop python2 from other code. What's your timeline?

**Comment by stanleybak** [comment]
Honestly, I'll start to have some cycles in December, so that's when I would suggest we do most of the work. I wouldn't mind rewriting some of the subprocess code, as if I remember correctly python 3's interface was better than python 2. The idea to include test metrics is good.

**Comment by MaxGaukler** [comment]
Starting in December sounds good - let me know then, so we can work together.
